# Generated by Django 5.1.2 on 2024-11-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_initial'),
    ]

    operations = [
        
    ]
