# Generated by Django 5.1.2 on 2024-11-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_table'),
    ]

    operations = [
        
    ]
