# Generated by Django 5.1.2 on 2024-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
    ]
