# Generated by Django 5.1.2 on 2024-11-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        
    ]
