# Generated by Django 5.1.2 on 2024-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_initial'),
    ]

    operations = [
        
    ]
